# Generated by Django 4.0 on 2021-12-19 05:31

from django.db import migrations, models
import django.db.models.deletion
import django_large_image.models.image
import s3_file_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_large_image', '0001_initial'),
        ('core', '0001_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImageFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', s3_file_field.fields.S3FileField()),
                (
                    'image',
                    django_large_image.models.image.LargeImageField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='large_image_file_source_%(app_label)s_%(class)s',
                        to='django_large_image.image',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
