# Generated by Django 4.0.3 on 2022-04-02 00:20

from django.db import migrations, models
import example.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_imagefile_id_alter_s3imagefile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLImageFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
            bases=(models.Model, example.core.models.Mixin),
        ),
    ]
