name: Publish Python Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: "*"

jobs:
  publish-wheels:
    name: Publish Wheels
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Build Wheel
        run: |
          pip install build
          python -m build
      - name: Deploy to PyPI on Tags
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Make index
        uses: banesullivan/create-pip-index-action@main
        with:
          package_directory: dist
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
