# Generated by Django 4.0.4 on 2022-04-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='data/')),
            ],
        ),
    ]
